#!/usr/bin/env python3

from prometheus_client import start_http_server, Gauge, Summary
from time import sleep
import argparse
import requests
import logging


BOND_STATUSES = {
    'BOND_STATUS_BONDED': 0,
    'BOND_STATUS_UNBONDING': 1,
    'BOND_STATUS_UNBONDED': 2,
}

code_strings = {
    2: b'01',
    3: b' ,.',
    10: b'0123456789',
    16: b'0123456789abcdef',
    32: b'abcdefghijklmnopqrstuvwxyz234567',
    58: b'123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz',
    256: b''.join([bytes((csx,)) for csx in range(256)]),
    'bech32': b'qpzry9x8gf2tvdw0s3jn54khce6mua7l'
}

balances_available_total = Gauge(
    name='balances_available_total',
    documentation='Total balances available to use across all balances',
    labelnames=[
        'delegator_address',
        'chain_id',
    ]
)

commissions_available = Gauge(
    name='commissions_available',
    documentation='Commissions available to withdraw from validators',
    labelnames=[
        'validator_address',
        'chain_id',
    ]
)

proposer_priority = Gauge(
    name='proposer_priority',
    documentation='The current validator proposer priority',
    labelnames=[
        'validator_address',
        'chain_id',
    ]
)

proposer_rank = Gauge(
    name='proposer_rank',
    documentation='The current validator proposer rank across all active validators',
    labelnames=[
        'validator_address',
        'chain_id',
    ]
)

rewards_available = Gauge(
    name='rewards_available',
    documentation='Rewards available to withdraw from validators',
    labelnames=[
        'delegator_address',
        'validator_address',
        'chain_id',
    ]
)

rewards_available_total = Gauge(
    name='rewards_available_total',
    documentation='Total rewards available to withdraw from all validators',
    labelnames=[
        'delegator_address',
        'chain_id',
    ]
)

# NOTE: Information to tune metrics update and scrape intervals based on total metrics collection duration.
total_processing_seconds = Summary('total_processing_seconds', 'Time spent to calculate all metric')

validator_jailed = Gauge(
    name='validator_jailed',
    documentation='The current validator jailed status (0 - unjailed, 1 - jailed, 2 - tombstoned)',
    labelnames=[
        'validator_address',
        'chain_id',
    ]
)

validator_rank = Gauge(
    name='validator_rank',
    documentation='The current validator rank across active validators',
    labelnames=[
        'validator_address',
        'chain_id',
    ]
)

validator_status = Gauge(
    name='validator_status',
    documentation='The current validator status (0 - bonded, 1 - unbonding, 2 - unbonded)',
    labelnames=[
        'validator_address',
        'chain_id',
    ]
)

validator_uptime = Gauge(
    name='validator_uptime',
    documentation='The current validator uptime',
    labelnames=[
        'validator_address',
        'chain_id',
    ]
)

# NOTE: This is a kind of debug information needed to check how many blocks we can check during single scrape interval.
uptime_processing_seconds = Summary('uptime_processing_seconds', 'Time spent to calculate uptime metric')


class CosmosRest(object):

    validators_total = 0

    def __init__(self, api_url: str = 'http://localhost:1317', rpc_url: str = 'http://127.0.0.1:26657',
                 version: str = 'v1beta1'):
        self.session = requests.Session()
        self.api_url = api_url
        self.rpc_url = rpc_url
        self.version = version

    def balances(self, delegator_address: str) -> dict:
        return self.session.get(
            url=f'{self.api_url}/bank/balances/{delegator_address}'
        ).json()['result'][0]

    def block(self, height: int) -> dict:
        return self.session.get(
            url=f'{self.rpc_url}/block',
            params={
                'height': height,
            }
        ).json()

    def blocks(self, height: str = 'latest') -> dict:
        return self.session.get(
            url=f'{self.api_url}/cosmos/base/tendermint/{self.version}/blocks/{height}'
        ).json()

    def commission(self, validator_address: str) -> list:
        return self.session.get(
            url=f'{self.api_url}/cosmos/distribution/{self.version}/validators/{validator_address}/commission'
        ).json()['commission']['commission']

    def rewards(self, delegator_address: str) -> dict:
        return self.session.get(
            url=f'{self.api_url}/cosmos/distribution/{self.version}/delegators/{delegator_address}/rewards'
        ).json()

    def signing_infos(self, consensus_address: str) -> dict:
        return self.session.get(
            url=f'{self.api_url}/cosmos/slashing/{self.version}/signing_infos/{consensus_address}'
        ).json()

    def status(self) -> dict:
        return self.session.get(
            url=f'{self.rpc_url}/status'
        ).json()['result']

    # TODO: Replace this function with SDK RPC query once https://github.com/cosmos/cosmos-sdk/pull/8567 will be done.
    # TODO: Use block_height to make sure queries will be done against the same block height.
    def validators_set(self, page: int = 1, per_page: int = 100) -> list:
        validators = list()
        while True:
            response = self.session.post(
                url=f'{self.rpc_url}',
                # TODO: In case of further integration, think about merging the dict with default and custom keys.
                json={
                    "jsonrpc": "2.0",
                    "id": 0,
                    "method": "validators",
                    "params": {
                        "page": f'{page}',
                        "per_page": f'{per_page}'
                    }
                }
            ).json()
            validators.extend(response['result']['validators'])
            if len(validators) == int(response['result']['total']):
                break
            page = page + 1
        return validators

    def validators(self, pagination_limit: int = validators_total) -> dict:
        response = self.session.get(
            url=f'{self.api_url}/cosmos/staking/{self.version}/validators',
            params={
                'pagination.limit': pagination_limit,
                'pagination.count_total': True,
            }
        )
        self.validators_total = int(response.json()['pagination']['total'])
        if len(response.json()['validators']) < self.validators_total:
            return self.validators(
                pagination_limit=self.validators_total
            )
        return response.json()['validators']


class Validator(object):

    def __init__(self, validator_address: str):
        for validator in api.validators():
            if validator['operator_address'] == validator_address:
                self.info = validator
        self.validator_address = validator_address

    def commissions(self, total: float = 0) -> float:
        for commission in api.commission(validator_address=self.validator_address):
            total += float(commission['amount'])
        return total / 10 ** 6


def _bech32_polymod(values):
    """
    Internal function that computes the Bech32 checksum

    Source: https://github.com/1200wd/bitcoinlib/blob/9507fbd035263cba5904bf0fdbb7f84bf549ffc0/bitcoinlib/encoding.py
    """
    generator = [0x3b6a57b2, 0x26508e6d, 0x1ea119fa, 0x3d4233dd, 0x2a1462b3]
    chk = 1
    for value in values:
        top = chk >> 25
        chk = (chk & 0x1ffffff) << 5 ^ value
        for i in range(5):
            chk ^= generator[i] if ((top >> i) & 1) else 0
    return chk


def addr_bech32_to_pubkeyhash(bech, prefix=None, include_witver=False, as_hex=False):
    """
    Decode bech32 / segwit address to public key hash

    Source: https://github.com/1200wd/bitcoinlib/blob/9507fbd035263cba5904bf0fdbb7f84bf549ffc0/bitcoinlib/encoding.py

    >>> addr_bech32_to_pubkeyhash('bc1qy8qmc6262m68ny0ftlexs4h9paud8sgce3sf84', as_hex=True)
    '21c1bc695a56f47991e95ff26856e50f78d3c118'

    Validate the bech32 string, and determine HRP and data. Only standard data size of 20 and 32 bytes are excepted

    :param bech: Bech32 address to convert
    :type bech: str
    :param prefix: Address prefix called Human-readable part. Default is None and tries to derive prefix, for bitcoin specify 'bc' and for bitcoin testnet 'tb'
    :type prefix: str
    :param include_witver: Include witness version in output? Default is False
    :type include_witver: bool
    :param as_hex: Output public key hash as hex or bytes. Default is False
    :type as_hex: bool

    :return str: Public Key Hash
    """
    if (any(ord(x) < 33 or ord(x) > 126 for x in bech)) or (bech.lower() != bech and bech.upper() != bech):
        raise Exception("Invalid bech32 character in bech string")
    bech = bech.lower()
    pos = bech.rfind('1')
    if pos < 1 or pos + 7 > len(bech) or len(bech) > 90:
        raise Exception("Invalid bech32 string length")
    if prefix and prefix != bech[:pos]:
        raise Exception("Invalid bech32 address. Prefix '%s', prefix expected is '%s'" % (bech[:pos], prefix))
    else:
        hrp = bech[:pos]
    data = _codestring_to_array(bech[pos + 1:], 'bech32')
    hrp_expanded = [ord(x) >> 5 for x in hrp] + [0] + [ord(x) & 31 for x in hrp]
    if not _bech32_polymod(hrp_expanded + data) == 1:
        raise Exception("Bech polymod check failed")
    data = data[:-6]
    decoded = bytes(convertbits(data, 5, 8, pad=False))
    if decoded is None or len(decoded) < 2 or len(decoded) > 20:
        raise Exception("Invalid decoded data length, must be between 2 and 40")
    if data[0] == 0 and len(decoded) not in [20, 32]:
        raise Exception("Invalid decoded data length, must be 20 or 32 bytes")
    prefix = b''
    if include_witver:
        datalen = len(decoded)
        prefix = bytes([data[0] + 0x50 if data[0] else 0, datalen])
    if as_hex:
        return (prefix + decoded).hex()
    return prefix + decoded


def _codestring_to_array(codestring, base):
    """
    Source: https://github.com/1200wd/bitcoinlib/blob/9507fbd035263cba5904bf0fdbb7f84bf549ffc0/bitcoinlib/encoding.py
    """
    codestring = bytes(codestring, 'utf8')
    codebase = code_strings[base]
    array = []
    for s in codestring:
        try:
            array.append(codebase.index(s))
        except ValueError:
            raise Exception("Character '%s' not found in codebase" % s)
    return array


def convertbits(data, frombits, tobits, pad=True):
    """
    'General power-of-2 base conversion'

    Source: https://github.com/sipa/bech32/tree/master/ref/python

    :param data: Data values to convert
    :type data: list
    :param frombits: Number of bits in source data
    :type frombits: int
    :param tobits: Number of bits in result data
    :type tobits: int
    :param pad: Use padding zero's or not. Default is True
    :type pad: bool

    :return list: Converted values
    """
    acc = 0
    bits = 0
    ret = []
    maxv = (1 << tobits) - 1
    max_acc = (1 << (frombits + tobits - 1)) - 1
    for value in data:
        if value < 0 or (value >> frombits):
            return None
        acc = ((acc << frombits) | value) & max_acc
        bits += frombits
        while bits >= tobits:
            bits -= tobits
            ret.append((acc >> bits) & maxv)
    if pad:
        if bits:
            ret.append((acc << (tobits - bits)) & maxv)
    elif bits >= frombits or ((acc << (tobits - bits)) & maxv):
        return None
    return ret


def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument('--api_url', help='Cosmos SDK instance API endpoint URL', type=str,
                        default='http://127.0.0.1:1317')
    parser.add_argument('--consensus_address', help='The validator consensus address to use', type=str, required=True)
    parser.add_argument('--delegator_address', help='The delegator account address to query stats', type=str,
                        required=True)
    parser.add_argument('--host', help='The network address to bind exporter too', type=str, default='0.0.0.0')
    parser.add_argument('--interval', help='Seconds between metrics refresh.', type=float, default=5.0)
    parser.add_argument(
        '--log_level', help='The logging level to use (default "info")', type=str, default='info', choices=[
            'warning',
            'debug',
            'info',
        ]
    )
    parser.add_argument('--port', help='The network port to bind exporter too', type=int, default=8000)
    parser.add_argument('--rpc_url', help='Tendermint instance RPC endpoint URL', type=str,
                        default='http://127.0.0.1:26657')
    parser.add_argument('--validator_address', help='The validator address to query stats', type=str, required=True)
    parser.add_argument('--uptime_window', help='Number of blocks to calculate node uptime', type=int, default=100)
    return parser


def priority(address: str, chain_id: str, validators: list) -> None:
    validators = sorted(validators, key=lambda k: int(k['proposer_priority']), reverse=True)
    for validator in validators:
        if validator['address'] == address:
            proposer_priority.labels(
                validator_address=known_args.validator_address,
                chain_id=chain_id,
            ).set(validator['proposer_priority'])
            proposer_rank.labels(
                validator_address=known_args.validator_address,
                chain_id=chain_id,
            ).set(validators.index(validator) + 1)
            break


def rank(address: str, chain_id: str, validators: list) -> None:
    validators = sorted(validators, key=lambda k: int(k['voting_power']), reverse=True)
    for validator in validators:
        if validator['address'] == address:
            validator_rank.labels(
                validator_address=known_args.validator_address,
                chain_id=chain_id,
            ).set(validators.index(validator) + 1)
            break


@uptime_processing_seconds.time()
def uptime(address: str, last_commit_height: int, uptime_window: int = 100) -> float:
    signatures: int = 0
    for height in range(last_commit_height - uptime_window, last_commit_height):
        for signature in api.block(height=height)['result']['block']['last_commit']['signatures']:
            if signature['validator_address'] and signature['validator_address'] == address:
                signatures = signatures + 1
                break
    return 100.0 * signatures / uptime_window


@total_processing_seconds.time()
def metrics(interval: int) -> float:
    logging.info('start')
    val = Validator(validator_address=known_args.validator_address)
    status = api.status()
    validator_jailed.labels(
        validator_address=val.validator_address,
        chain_id=status['node_info']['network'],
    ).set(int(val.info['jailed']))
    validator_status.labels(
        validator_address=val.validator_address,
        chain_id=status['node_info']['network'],
    ).set(BOND_STATUSES[val.info['status']])
    balances_available_total.labels(
        delegator_address=known_args.delegator_address,
        chain_id=status['node_info']['network'],
    ).set(float(api.balances(delegator_address=known_args.delegator_address)['amount']) / 10 ** 6)
    commissions_available.labels(
        validator_address=val.validator_address,
        chain_id=status['node_info']['network'],
    ).set(val.commissions())
    validators = api.validators_set()
    priority(
        address=validator_hex_address,
        chain_id=status['node_info']['network'],
        validators=validators,
    )
    rank(
        address=validator_hex_address,
        chain_id=status['node_info']['network'],
        validators=validators,
    )
    rewards = api.rewards(delegator_address=known_args.delegator_address)
    for reward in rewards['rewards']:
        rewards_available.labels(
            delegator_address=known_args.delegator_address,
            validator_address=reward['validator_address'],
            chain_id=status['node_info']['network'],
        ).set(float(reward['reward'][0]['amount']) / 10 ** 6)
    rewards_available_total.labels(
        delegator_address=known_args.delegator_address,
        chain_id=status['node_info']['network'],
    ).set(float(rewards['total'][0]['amount']) / 10 ** 6)
    validator_jailed.labels(
        validator_address=known_args.validator_address,
        chain_id=status['node_info']['network'],
    ).set(
        int(val.info['jailed']) if not api.signing_infos(
            consensus_address=known_args.consensus_address)['val_signing_info']['tombstoned']
        else 2
    )
    validator_status.labels(
        validator_address=known_args.validator_address,
        chain_id=status['node_info']['network'],
    ).set(BOND_STATUSES[val.info['status']])
    validator_uptime.labels(
        validator_address=val.validator_address,
        chain_id=status['node_info']['network'],
    ).set(
        uptime(
            address=validator_hex_address,
            last_commit_height=int(status['sync_info']['latest_block_height']) - 1,
            uptime_window=known_args.uptime_window,
        )
    )
    logging.info('finish')
    # TODO: Return metrics interval minus the last iteration execution time.
    return interval


def main() -> None:
    # NOTE: I am just cannot see single and relatively large line, this is why use cascade here.
    while True:
        sleep(
            metrics(
                interval=known_args.interval,
            )
        )


if __name__ == '__main__':
    known_args, unknown_args = parse_arguments().parse_known_args()
    logging.basicConfig(level=logging.getLevelName(known_args.log_level.upper()))
    start_http_server(addr=known_args.host, port=known_args.port)
    # TODO: Keep tracking https://github.com/cosmos/cosmos-sdk/pull/8567 and remove use of public key hash in HEX format
    validator_hex_address = addr_bech32_to_pubkeyhash(
        bech=known_args.consensus_address,
        as_hex=True
    ).upper()
    api = CosmosRest(
        api_url=known_args.api_url,
        rpc_url=known_args.rpc_url,
    )
    main()
